CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    customer_id BIGINT,
    discount_amount NUMERIC(12,2) NOT NULL,
    notes VARCHAR(1000),
    payment_status VARCHAR(255) NOT NULL,
    sale_date TIMESTAMP(6),
    sale_number VARCHAR(255),
    sale_status VARCHAR(255) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    tax_amount NUMERIC(12,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    CONSTRAINT uk_sales_sale_number UNIQUE (sale_number),
    CONSTRAINT sales_payment_status_check CHECK (payment_status IN ('PENDING','PARTIALLY_PAID','PAID','FAILED','REFUNDED')),
    CONSTRAINT sales_sale_status_check CHECK (sale_status IN ('CREATED','COMPLETED','CANCELLED','RETURNED'))
);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_amount NUMERIC(12,2) NOT NULL,
    product_variant_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    tax_amount NUMERIC(12,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    sale_id BIGINT NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    notes VARCHAR(500),
    payment_date TIMESTAMP(6),
    payment_method VARCHAR(255) NOT NULL,
    payment_status VARCHAR(255) NOT NULL,
    transaction_reference VARCHAR(100),
    sale_id BIGINT NOT NULL,
    CONSTRAINT payments_payment_method_check CHECK (payment_method IN ('CASH','CARD','UPI','NET_BANKING','WALLET','CHEQUE','OTHER')),
    CONSTRAINT payments_payment_status_check CHECK (payment_status IN ('PENDING','PARTIALLY_PAID','PAID','FAILED','REFUNDED')),
    CONSTRAINT fk_payments_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
);
