-- Flyway migration: basic invoices and items
CREATE TABLE invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number varchar(20) NOT NULL UNIQUE,
  sale_id bigint NOT NULL UNIQUE,
  customer_id bigint NOT NULL,
  subtotal numeric(18,2) NOT NULL,
  tax_amount numeric(18,2) NOT NULL,
  discount_amount numeric(18,2) NOT NULL,
  total numeric(18,2) NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'INR',
  payment_method varchar(100),
  payment_status varchar(50),
  transaction_reference varchar(200),
  paid_amount numeric(18,2),
  paid_at timestamp,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  product_id bigint,
  variant_id bigint,
  sku varchar(100),
  barcode varchar(100),
  product_name varchar(255),
  variant_name varchar(255),
  quantity integer NOT NULL,
  unit_price numeric(18,2),
  discount_amount numeric(18,2),
  tax_amount numeric(18,2),
  line_total numeric(18,2),
  CONSTRAINT fk_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);
