CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    address VARCHAR(500),
    contact_person VARCHAR(100),
    email VARCHAR(150),
    gst_number VARCHAR(20),
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    CONSTRAINT uk_suppliers_gst_number UNIQUE (gst_number),
    CONSTRAINT uk_suppliers_phone UNIQUE (phone)
);

CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    purchase_date DATE NOT NULL,
    purchase_number VARCHAR(50) NOT NULL,
    remarks VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    total_amount NUMERIC(15,2) NOT NULL,
    supplier_id BIGINT NOT NULL,
    CONSTRAINT uk_purchases_purchase_number UNIQUE (purchase_number),
    CONSTRAINT purchases_status_check CHECK (status IN ('DRAFT','APPROVED','RECEIVED','CANCELLED')),
    CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    product_variant_id BIGINT NOT NULL,
    purchase_price NUMERIC(15,2) NOT NULL,
    quantity INTEGER NOT NULL,
    purchase_id BIGINT NOT NULL,
    CONSTRAINT fk_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id)
);
