CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    anniversary DATE,
    created_at TIMESTAMP(6) NOT NULL,
    customer_code VARCHAR(25) NOT NULL,
    customer_status VARCHAR(20) NOT NULL,
    date_of_birth DATE,
    email VARCHAR(150),
    first_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    last_name VARCHAR(100),
    mobile_number VARCHAR(20),
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_customers_mobile_number UNIQUE (mobile_number),
    CONSTRAINT uk_customers_customer_code UNIQUE (customer_code),
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT customers_customer_status_check CHECK (customer_status IN ('ACTIVE','INACTIVE','BLOCKED')),
    CONSTRAINT customers_gender_check CHECK (gender IN ('MALE','FEMALE','OTHER'))
);

CREATE INDEX idx_customer_code ON customers(customer_code);
CREATE INDEX idx_customer_email ON customers(email);
CREATE INDEX idx_customer_mobile ON customers(mobile_number);

CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    address_type VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    default_address BOOLEAN NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    state VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    customer_id BIGINT NOT NULL,
    CONSTRAINT customer_addresses_address_type_check CHECK (address_type IN ('HOME','OFFICE','OTHER')),
    CONSTRAINT fk_customer_addresses_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_customer_address_customer ON customer_addresses(customer_id);
