CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL,
    name VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_locked BOOLEAN NOT NULL,
    account_locked_until TIMESTAMP(6),
    created_at TIMESTAMP(6),
    created_by VARCHAR(255),
    email VARCHAR(255),
    failed_login_attempts INTEGER NOT NULL,
    force_password_change BOOLEAN NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL,
    last_login_at TIMESTAMP(6),
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    updated_at TIMESTAMP(6),
    username VARCHAR(50) NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone UNIQUE (phone),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
