spring.application.name=billing-service
server.port=9096

spring.datasource.url=jdbc:postgresql://localhost:5432/retail_billing
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

sales-service.url=http://localhost:9093
sales-service.connect-timeout=5s
sales-service.read-timeout=10s

customer-service.url=http://localhost:9094
customer-service.connect-timeout=5s
customer-service.read-timeout=10s
