CREATE TABLE attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    data_type VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    name VARCHAR(100) NOT NULL,
    required BOOLEAN NOT NULL,
    CONSTRAINT uk_attributes_name UNIQUE (name),
    CONSTRAINT attributes_data_type_check CHECK (data_type IN ('TEXT','INTEGER','DECIMAL','BOOLEAN','DATE','COLOR','EMAIL','URL','JSON'))
);

CREATE TABLE attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    value VARCHAR(100) NOT NULL,
    attribute_id BIGINT NOT NULL,
    CONSTRAINT uk_attribute_values_attribute_value UNIQUE (attribute_id, value),
    CONSTRAINT fk_attribute_values_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(id)
);

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    description VARCHAR(500) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_brands_name UNIQUE (name)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    description VARCHAR(500) NOT NULL,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    description VARCHAR(1000) NOT NULL,
    has_variants BOOLEAN NOT NULL,
    name VARCHAR(150) NOT NULL,
    product_code VARCHAR(50),
    brand_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT uk_products_product_code UNIQUE (product_code),
    CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    barcode VARCHAR(100),
    minimum_selling_price NUMERIC(10,2) NOT NULL,
    purchase_price NUMERIC(10,2) NOT NULL,
    selling_price NUMERIC(10,2) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT uk_product_variants_sku UNIQUE (sku),
    CONSTRAINT uk_product_variants_barcode UNIQUE (barcode),
    CONSTRAINT fk_product_variants_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    current_stock INTEGER NOT NULL,
    maximum_stock INTEGER,
    minimum_stock INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    reserved_stock INTEGER NOT NULL,
    product_variant_id BIGINT NOT NULL,
    CONSTRAINT uk_inventories_product_variant UNIQUE (product_variant_id),
    CONSTRAINT fk_inventories_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    display_order INTEGER NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    is_primary BOOLEAN NOT NULL,
    product_variant_id BIGINT NOT NULL,
    CONSTRAINT fk_product_images_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    adjustment_type VARCHAR(255),
    movement_type VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    reference_number VARCHAR(100),
    reference_type VARCHAR(50),
    remarks VARCHAR(500),
    inventory_id BIGINT NOT NULL,
    CONSTRAINT stock_movements_adjustment_type_check CHECK (adjustment_type IN ('INCREASE','DECREASE')),
    CONSTRAINT stock_movements_movement_type_check CHECK (movement_type IN ('PURCHASE','SALE','RETURN','ADJUSTMENT','RESERVE','UNRESERVE','DAMAGE')),
    CONSTRAINT stock_movements_reference_type_check CHECK (reference_type IN ('PURCHASE_ORDER','SALES_INVOICE','SALES_RETURN','MANUAL_ADJUSTMENT','DAMAGE_REPORT','ORDER_RESERVATION')),
    CONSTRAINT fk_stock_movements_inventory FOREIGN KEY (inventory_id) REFERENCES inventories(id)
);

CREATE TABLE variant_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by BIGINT,
    is_active BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by BIGINT,
    version BIGINT,
    attribute_id BIGINT NOT NULL,
    attribute_value_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,
    CONSTRAINT uk_variant_attributes_variant_attribute UNIQUE (product_variant_id, attribute_id),
    CONSTRAINT fk_variant_attributes_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(id),
    CONSTRAINT fk_variant_attributes_attribute_value FOREIGN KEY (attribute_value_id) REFERENCES attribute_values(id),
    CONSTRAINT fk_variant_attributes_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
);
